### ISSUE TITLE
Issue erasing objects

### ISSUE THREAD

**Issue by 2024andietrich** [davenquinn/Mapboard-GIS#16]
Hello:
Checking out the new 4.1.0. Got problems with erasing some lines. Most lines were no problem to erase, but I am stuck with 3 stubborn lines belonging to two line types which do not disappear. After applying the erase tool I am asked by MapboardGIS if I want to erase those features, but they simply do not go away. Exited the project and tried it again, they stay. Tried to select them with the selection tool and then try to delete, they stay.

**Comment by 2024andietrich** [comment]
Sorry Daven for bothering yesterday. Finally found the problem which was that these lines for some reason (unawareness) were digitized in the GRID layer. So problem solved. By the way my congratulations to this outstanding product! I use it now since 2-3 years and am very happy, it does not compare to any other mobile GIS app. Cheers, Andreas

**Comment by davenquinn** [comment]
@2024andietrich –
Glad you found a quick solution. I’m working on an update that adds a “show only this layer” mode, which should make this easier to diagnose in the future. 

Glad you enjoy the app! Don't hesitate to suggest features or simplifications that might benefit your use case.

**Comment by 2024andietrich** [comment]
Hi Daven:Now that you ask for suggestions - what got me frequently into trouble is the limitation to demo mode (50 moves) while MapboardGIS cannot re-establish a purchased subscription. As a field mapping geologist I happen to be frequently without internet connection and then occasionally stuck with demo mode. Being a mapper yourself you see the inconvenience.
Cheers,Andreas


Gesendet von Yahoo Mail für iPad


Am Sonntag, April 14, 2024, 18:44 schrieb Daven Quinn ***@***.***>:




@2024andietrich –
Glad you found a quick solution. I’m working on an update that adds a “show only this layer” mode, which should make this easier to diagnose in the future.

Glad you enjoy the app! Don't hesitate to suggest features or simplifications that might benefit your use case.
