### ISSUE TITLE
Unable to add mbtile file from local iPad folder

### ISSUE THREAD

**Issue by mateo3571** [davenquinn/Mapboard-GIS#9]
Subscription Info: 
![MAPBOARD SUBSCRIPTION INFO](https://user-images.githubusercontent.com/44346622/180310080-ce696b6f-08a6-4a9a-9922-bae12b10abb7.jpg)

Error in mobile app UI when <Done> (after uploading a mbtiles raster from my local iPad folder) 
![MBTILES FROM FILE on IPAD](https://user-images.githubusercontent.com/44346622/180310246-f5ead48d-6df3-4363-bcce-33bae365d3e9.jpg)

**Comment by davenquinn** [comment]
Thanks for the bug report!

It looks like the issue may be that the app doesn't deal well with MBTiles files with spaces in the filenames. Can you try renaming your file to have no spaces, and see if that solves the issue? If it does, that's a bug but one with a clear workaround for now.

**Comment by mateo3571** [comment]
Renamed mbtiles file to have no spaces or underscores, etc. Same error displays. I tried to attached one of the offending mbtiles for your reference but mbtile file type is not supported.

**Comment by davenquinn** [comment]
Thanks for testing — could you email the file directly to ***@***.***?

**Comment by davenquinn** [comment]
Another option for debugging: The only place in Mapboard's codebase that particular error is thrown is after a "sanity check" were we connect to the database and run the SQL query `SELECT tile_data FROM tiles LIMIT 1` against it.

This query should succeed if the MBTiles file is a properly formed SQLite database with the appropriate tables for MBTiles. You could check in an SQLite reader (e.g., SQLiteBrowser) to see if you have the requisite tables and that query succeeds.

**Comment by mateo3571** [comment]
Thanks for the replies. The file is too big to email directly. Here’s a a
Dropbox link to the mbtiles file in question.

https://www.dropbox.com/s/mkl4hpn8ri29oc3/01ENCagsChartPDF.mbtiles?dl=0

Thanks.

Matt

**Comment by mateo3571** [comment]
Hi Daven,
I've created mbtiles in QGIS, Global Mapper, MapTiler Desktop, My GeoData
Converter and Ubuntu and Mapboard GIS throws an error on all of them. It
must be something I'm doing wrong when setting up a project because I can't
imagine all of those programs are compiling the mbtiles files incorrectly
so Mapboard GIS rejects them. I loaded one of the mbtiles files which
Mapboard rejected into the SQLite Browser utility and ran the SQL Statement
reference in your last email. The results are in the screenshot below.

[image: MapBoard SQL Statement test_1.png]
[image: MapBoard SQL Statement test_2.png]


Thanks.

**Comment by davenquinn** [comment]
Hi Mateo,

The screenshots didn't load but thanks for your checking, and sorry this is frustrating.

For what it's worth, I have just tested your MBTiles file on my latest development version of Mapboard (which has some significant changes to the mapping engine from the current version) and it show up just fine.

So – you are encountering a bug that I have since corrected, although the fix is not public. I'll try to get the new version out shortly to mitigate this.

Thanks again for the report.

**Comment by mateo3571** [comment]
Great. Thanks Daven!

**Comment by mateo3571** [comment]
Hello Daven. 
Any updates on the latest version of the Mapboard GIS mobile app for iOS with the mbtiles fix in it? 

Thanks. 
Matt

**Comment by davenquinn** [comment]
Hi Matt,

This one's proving a headache because there's a major map system update (Mapbox iOS SDK -> Mapbox Maps SDK) that has to be weaved in, which has occasioned a major rewrite of far too many things. Still, it's getting closer by the day, and there's a lot of advances in the new version. I will release a beta soon and let you know when that's available to try.

Best,
Daven

**Comment by davenquinn** [comment]
Hi @mateo3571, a new beta for Mapboard GIS is available on [TestFlight](https://testflight.apple.com/join/0TfVlWyN) that fixes this and many other issues. Feel free to provide feedback on this or other issues.

**Comment by davenquinn** [comment]
The fixes for this bug have now been released in Mapboard GIS v3.2.0 and v3.3.0. Please check those out!

**Comment by mateo3571** [comment]
Hi David,
While I was successful with  importing a select few  mbtiles files - image
overlays,  into Mapboard, the majority of mbtiles fail to display after
importing them various file storage resources including the local folders
on my iPad. All SQLite files failed to import. I couldn’t identify a common
pattern as to why most didn’t load into Mapboard and two or so that did
import. Btw, it didn’t matter if a mbtiles file successfully imported into
the app or not, there were errors 100% of the time directly after the file
showed up in the app.

I’ve attached some screenshots below. I know I suck at defect validation
and user acceptance testing because I provide little to no detail in the
steps to reproduce. It wouldn’t surprise me if I missed a backend setting
that resolves my issue but the errors are pretty generic in nature.

Btw, I’ve been trying out what seems like 100’s of mobile apps to identify
an app which can support large file sizes associated with hydrographic
sonar data while offline. I saw that the 3D terrain was implemented in
Mapboard and that was very cool. I don’t see any means for me to import my
elevation data into the app that could used as a bathymetric seafloor model
which I would drape my hi-res (50cm-1m) raster mosaics on. For fishing,
diving and some reef building efforts. I’ve used Map Plus for years to run
my charts but I want to sell my data to people that would load the files
into an app like Map Plus. Map Plus is kinda difficult for most fisherman
types to grasp, so not suitable as hosting platform for hi-res bathy app
that hosts hi-res datasets.

**Comment by davenquinn** [comment]
Hi @mateo3571,

I don't see the screenshots here. Have you checked the Developer Settings > Event Log to see if there is a specific error message thrown?

As far as importing elevation data for terrain modeling, right now the app has very limited functionality in this regard (essentially, Mapbox's own elevation datasets). I'm working on some server-side solutions to increase the breadth of this, but it is a large problem space. Over the next few years, I am keen to evolve in this direction.

If you had an external data system that hosted clean bathymetric datasets in COG format, I've experimented with some servers that could tile them and provide for usage in the app. Perhaps we could have a call sometime to discuss what would be needed for Mapboard to host such a system.

**Comment by mateo3571** [comment]
2 of 5 screenshot sent

**Comment by davenquinn** [comment]
It appears that screenshots sent via email are not shown on the GitHub issue page. Can you upload them directly at https://github.com/davenquinn/Mapboard-GIS/issues/9?
